IMPORTATION ET EXPLORATION

In [149]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\user\Desktop\superstore\store.csv')

filling the missing postal code using mapping method

In [154]:
mapping = df.dropna(subset=['Postal Code']).set_index('City')['Postal Code'].to_dict()

df['Postal Code'] = df['Postal Code'].fillna(df['City'].map(mapping))

changing the date format

In [200]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')

converting ("Postal Code") type into string

In [202]:
df['Postal Code'] = df['Postal Code'].astype(int).astype(str)

Nettoyage

In [160]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='str')

In [161]:
df.sample(10,random_state=42)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
532,533,US-2018-129441,2018-09-07,2018-09-11,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,Los Angeles,California,90032,West,FUR-FU-10000448,Furniture,Furnishings,Tenex Chairmats For Use With Carpeted Floors,47.940
872,873,CA-2015-148488,2015-12-10,2015-12-15,Standard Class,SM-20005,Sally Matthias,Consumer,United States,New York City,New York,10009,East,OFF-PA-10004470,Office Supplies,Paper,"Adams Write n' Stick Phone Message Book, 11"" X...",11.360
1149,1150,CA-2016-112452,2016-04-04,2016-04-04,Same Day,NC-18340,Nat Carroll,Consumer,United States,Lansing,Michigan,48911,Central,TEC-PH-10000307,Technology,Phones,Shocksock Galaxy S4 Armband,10.950
2287,2288,US-2018-112928,2018-06-01,2018-06-05,Second Class,BB-10990,Barry Blumstein,Corporate,United States,Toledo,Ohio,43615,East,OFF-AP-10002287,Office Supplies,Appliances,Eureka Sanitaire Multi-Pro Heavy-Duty Upright...,17.480
4038,4039,CA-2015-110786,2015-12-29,2016-01-02,Standard Class,AJ-10795,Anthony Johnson,Corporate,United States,San Francisco,California,94110,West,OFF-PA-10000528,Office Supplies,Paper,Xerox 1981,21.120
1726,1727,CA-2016-127453,2016-12-19,2016-12-20,First Class,JK-15370,Jay Kimmel,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AP-10003860,Office Supplies,Appliances,Fellowes Advanced 8 Outlet Surge Suppressor wi...,88.832
4989,4990,CA-2018-107321,2018-08-31,2018-09-04,Standard Class,AW-10930,Arthur Wiediger,Home Office,United States,San Francisco,California,94110,West,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,6.672
4228,4229,CA-2017-113803,2017-03-24,2017-03-26,First Class,VG-21805,Vivek Grady,Corporate,United States,Richmond,Indiana,47374,Central,OFF-PA-10001994,Office Supplies,Paper,"Ink Jet Note and Greeting Cards, 8-1/2"" x 5-1/...",22.480
6664,6665,CA-2018-162173,2018-10-26,2018-11-01,Standard Class,OT-18730,Olvera Toch,Consumer,United States,Virginia Beach,Virginia,23464,South,OFF-EN-10002831,Office Supplies,Envelopes,"Tyvek Top-Opening Peel & Seel Envelopes, Gray",251.580
7598,7599,CA-2015-131947,2015-09-17,2015-09-22,Standard Class,JA-15970,Joseph Airdo,Consumer,United States,Springfield,Oregon,97477,West,OFF-AR-10000411,Office Supplies,Art,Boston 16701 Slimline Battery Pencil Sharpener,38.256

In [162]:
text_columns = ['Customer Name', 'City', 'State', 'Product Name', 'Category', 'Sub-Category']

for col in text_columns:
    df[col] = df[col].str.strip().str.title()

df['Order ID'] = df['Order ID'].str.strip().str.upper()
df['Product ID'] = df['Product ID'].str.strip().str.upper()

In [163]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [164]:
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month_name()
df['Order Day'] = df['Order Date'].dt.day

In [165]:
df['Segment'] = df['Segment'].str.strip().str.title()
df['Ship Mode'] = df['Ship Mode'].str.strip().str.title()
df['Region'] = df['Region'].str.strip().str.title()

In [166]:
df_alt = df.copy()

In [167]:
df_alt.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   datetime64[us]
 3   Ship Date      9800 non-null   datetime64[us]
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9800 non-null   str
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
 18  Order Year     9800 non-null   int32
 19  Order Month    9800 non-null   str
 20  Order Day      9800 non-null   int32
dtypes: datetime64[us](2), float64(1), int32(2), int64(1), str(15)
memory usage: 1.5 MB

In [168]:
df_alt.sample(10,random_state=42)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Order Year,Order Month,Order Day
532,533,US-2018-129441,2018-09-07,2018-09-11,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10000448,Furniture,Furnishings,Tenex Chairmats For Use With Carpeted Floors,47.940,2018,September,7
872,873,CA-2015-148488,2015-12-10,2015-12-15,Standard Class,SM-20005,Sally Matthias,Consumer,United States,New York City,...,10009,East,OFF-PA-10004470,Office Supplies,Paper,"Adams Write N' Stick Phone Message Book, 11"" X...",11.360,2015,December,10
1149,1150,CA-2016-112452,2016-04-04,2016-04-04,Same Day,NC-18340,Nat Carroll,Consumer,United States,Lansing,...,48911,Central,TEC-PH-10000307,Technology,Phones,Shocksock Galaxy S4 Armband,10.950,2016,April,4
2287,2288,US-2018-112928,2018-06-01,2018-06-05,Second Class,BB-10990,Barry Blumstein,Corporate,United States,Toledo,...,43615,East,OFF-AP-10002287,Office Supplies,Appliances,Eureka Sanitaire Multi-Pro Heavy-Duty Upright...,17.480,2018,June,1
4038,4039,CA-2015-110786,2015-12-29,2016-01-02,Standard Class,AJ-10795,Anthony Johnson,Corporate,United States,San Francisco,...,94110,West,OFF-PA-10000528,Office Supplies,Paper,Xerox 1981,21.120,2015,December,29
1726,1727,CA-2016-127453,2016-12-19,2016-12-20,First Class,JK-15370,Jay Kimmel,Consumer,United States,Philadelphia,...,19143,East,OFF-AP-10003860,Office Supplies,Appliances,Fellowes Advanced 8 Outlet Surge Suppressor Wi...,88.832,2016,December,19
4989,4990,CA-2018-107321,2018-08-31,2018-09-04,Standard Class,AW-10930,Arthur Wiediger,Home Office,United States,San Francisco,...,94110,West,OFF-BI-10004022,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,6.672,2018,August,31
4228,4229,CA-2017-113803,2017-03-24,2017-03-26,First Class,VG-21805,Vivek Grady,Corporate,United States,Richmond,...,47374,Central,OFF-PA-10001994,Office Supplies,Paper,"Ink Jet Note And Greeting Cards, 8-1/2"" X 5-1/...",22.480,2017,March,24
6664,6665,CA-2018-162173,2018-10-26,2018-11-01,Standard Class,OT-18730,Olvera Toch,Consumer,United States,Virginia Beach,...,23464,South,OFF-EN-10002831,Office Supplies,Envelopes,"Tyvek Top-Opening Peel & Seel Envelopes, Gray",251.580,2018,October,26
7598,7599,CA-2015-131947,2015-09-17,2015-09-22,Standard Class,JA-15970,Joseph Airdo,Consumer,United States,Springfield,...,97477,West,OFF-AR-10000411,Office Supplies,Art,Boston 16701 Slimline Battery Pencil Sharpener,38.256,2015,September,17

In [169]:
df_alt['Order Quarter'] = df_alt['Order Date'].dt.to_period('Q').astype(str)

print(df_alt['Order Quarter'].head())

0    2017Q4
1    2017Q4
2    2017Q2
3    2016Q4
4    2016Q4
Name: Order Quarter, dtype: str

In [170]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Order Year', 'Order Month', 'Order Day']

In [171]:
df.sample(5,random_state=42)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Order Year,Order Month,Order Day
532,533,US-2018-129441,2018-09-07,2018-09-11,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10000448,Furniture,Furnishings,Tenex Chairmats For Use With Carpeted Floors,47.94,2018,September,7
872,873,CA-2015-148488,2015-12-10,2015-12-15,Standard Class,SM-20005,Sally Matthias,Consumer,United States,New York City,...,10009,East,OFF-PA-10004470,Office Supplies,Paper,"Adams Write N' Stick Phone Message Book, 11"" X...",11.36,2015,December,10
1149,1150,CA-2016-112452,2016-04-04,2016-04-04,Same Day,NC-18340,Nat Carroll,Consumer,United States,Lansing,...,48911,Central,TEC-PH-10000307,Technology,Phones,Shocksock Galaxy S4 Armband,10.95,2016,April,4
2287,2288,US-2018-112928,2018-06-01,2018-06-05,Second Class,BB-10990,Barry Blumstein,Corporate,United States,Toledo,...,43615,East,OFF-AP-10002287,Office Supplies,Appliances,Eureka Sanitaire Multi-Pro Heavy-Duty Upright...,17.48,2018,June,1
4038,4039,CA-2015-110786,2015-12-29,2016-01-02,Standard Class,AJ-10795,Anthony Johnson,Corporate,United States,San Francisco,...,94110,West,OFF-PA-10000528,Office Supplies,Paper,Xerox 1981,21.12,2015,December,29

In [172]:
df['Profit'] = df['Sales'] * 0.30

df['Profit Margin %'] = (df['Profit'] / df['Sales']) * 100

df['Profit Margin %'] = df['Profit Margin %'].round(2)

print(df[['Sales', 'Profit', 'Profit Margin %']].head())

      Sales     Profit  Profit Margin %
0  261.9600   78.58800             30.0
1  731.9400  219.58200             30.0
2   14.6200    4.38600             30.0
3  957.5775  287.27325             30.0
4   22.3680    6.71040             30.0

In [173]:
cat_columns = ['Segment', 'Category', 'Sub-Category', 'Region', 'Ship Mode', 'State']

for col in cat_columns:
    df[col] = df[col].astype('category')

print(df[cat_columns].dtypes)

Segment         category
Category        category
Sub-Category    category
Region          category
Ship Mode       category
State           category
dtype: object

In [174]:
bins = [0, 100, 1000, df['Sales'].max()]
labels = ['Low Sales', 'Medium Sales', 'High Sales']

df['Sales_Performance'] = pd.cut(df['Sales'], bins=bins, labels=labels)

In [175]:
def categorize_profit(margin):
    if margin > 20: return 'Highly Profitable'
    elif margin > 0: return 'Profitable'
    else: return 'Loss'

df['Profitability_Status'] = df['Profit Margin %'].apply(categorize_profit)

In [176]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9800 non-null   int64
 1   Order ID              9800 non-null   str
 2   Order Date            9800 non-null   datetime64[us]
 3   Ship Date             9800 non-null   datetime64[us]
 4   Ship Mode             9800 non-null   category
 5   Customer ID           9800 non-null   str
 6   Customer Name         9800 non-null   str
 7   Segment               9800 non-null   category
 8   Country               9800 non-null   str
 9   City                  9800 non-null   str
 10  State                 9800 non-null   category
 11  Postal Code           9800 non-null   str
 12  Region                9800 non-null   category
 13  Product ID            9800 non-null   str
 14  Category              9800 non-null   category
 15  Sub-Category          9800 non-null   category
 16  Product Name          9800 non-null   str
 17  Sales                 9800 non-null   float64
 18  Order Year            9800 non-null   int32
 19  Order Month           9800 non-null   str
 20  Order Day             9800 non-null   int32
 21  Profit                9800 non-null   float64
 22  Profit Margin %       9800 non-null   float64
 23  Sales_Performance     9800 non-null   category
 24  Profitability_Status  9800 non-null   str
dtypes: category(7), datetime64[us](2), float64(3), int32(2), int64(1), str(10)
memory usage: 1.3 MB

In [193]:
df.describe()

,Row ID,Order Date,Ship Date,Sales,Profit,Estimated Cost,Profit Margin %,ROI_Factor,Ship Delay,Order Year,Order Day
count,9800.000000,9800,9800,9800.000000,9800.000000,9800.000000,9800.0,9.800000e+03,9800.000000,9800.000000,9800.000000
mean,4900.500000,2017-05-01 05:13:51.673469,2017-05-05 04:17:52.653061,230.769059,69.230718,161.538342,30.0,4.285714e-01,3.961122,2016.724184,15.486837
min,1.000000,2015-01-03 00:00:00,2015-01-07 00:00:00,0.444000,0.133200,0.310800,30.0,4.285714e-01,0.000000,2015.000000,1.000000
25%,2450.750000,2016-05-24 00:00:00,2016-05-27 18:00:00,17.248000,5.174400,12.073600,30.0,4.285714e-01,3.000000,2016.000000,8.000000
50%,4900.500000,2017-06-26 00:00:00,2017-06-29 00:00:00,54.490000,16.347000,38.143000,30.0,4.285714e-01,4.000000,2017.000000,16.000000
75%,7350.250000,2018-05-15 00:00:00,2018-05-19 00:00:00,210.605000,63.181500,147.423500,30.0,4.285714e-01,5.000000,2018.000000,23.000000
max,9800.000000,2018-12-30 00:00:00,2019-01-05 00:00:00,22638.480000,6791.544000,15846.936000,30.0,4.285714e-01,7.000000,2018.000000,31.000000
std,2829.160653,NaN,NaN,626.651875,187.995562,438.656312,0.0,3.783056e-17,1.749614,1.123984,8.753733

In [178]:
df['Ship Delay'] = (df['Ship Date'] - df['Order Date']).dt.days

def ship_speed(days):
    if days <= 2: return 'Express'
    elif days <= 5: return 'Standard'
    else: return 'Late'

df['Shipping Class'] = df['Ship Delay'].apply(ship_speed)

In [179]:
df['Estimated Cost'] = df['Sales'] - df['Profit']

df['ROI_Factor'] = df['Profit'] / df['Estimated Cost']

df['Is_Profitable'] = df['Profit'] > 0

import numpy as np
df['ROI_Factor'] = df['ROI_Factor'].replace([np.inf, -np.inf], 0).fillna(0)

print(df[['Sales', 'Profit', 'Estimated Cost', 'ROI_Factor']].head())

      Sales     Profit  Estimated Cost  ROI_Factor
0  261.9600   78.58800       183.37200    0.428571
1  731.9400  219.58200       512.35800    0.428571
2   14.6200    4.38600        10.23400    0.428571
3  957.5775  287.27325       670.30425    0.428571
4   22.3680    6.71040        15.65760    0.428571

In [180]:
total_sales = df['Sales'].sum()
df['Sales_Weight_%'] = (df['Sales'] / total_sales) * 100

In [181]:
region_analysis = df.groupby('Region').agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Profit Margin %': 'mean',
    'Order ID': 'count'
}).rename(columns={'Order ID': 'Total Orders'}).sort_values(by='Profit', ascending=False)

print(region_analysis)

               Sales        Profit  Profit Margin %  Total Orders
Region
West     710219.6845  213065.90535             30.0          3140
East     669518.7260  200855.61780             30.0          2785
Central  492646.9132  147794.07396             30.0          2277
South    389151.4590  116745.43770             30.0          1598

In [182]:
product_performance = df.groupby('Product Name').agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'ROI_Factor': 'mean'
}).sort_values(by='Sales', ascending=False).head(10)

print(product_performance)

                                                        Sales      Profit  \
Product Name
Canon Imageclass 2200 Advanced Copier               61599.824  18479.9472
Fellowes Pb500 Electric Punch Plastic Comb Bind...  27453.384   8236.0152
Cisco Telepresence System Ex90 Videoconferencin...  22638.480   6791.5440
Hon 5400 Series Task Chairs For Big And Tall        21870.576   6561.1728
Gbc Docubind Tl300 Electric Binding System          19823.479   5947.0437
Gbc Ibimaster 500 Manual Proclick Binding System    19024.500   5707.3500
Hewlett Packard Laserjet 3310 Copier                18839.686   5651.9058
Hp Designjet T520 Inkjet Large Format Printer -...  18374.895   5512.4685
Gbc Docubind P400 Electric Binding System           17965.068   5389.5204
High Speed Automatic Electric Letter Opener         17030.312   5109.0936

                                                    ROI_Factor
Product Name
Canon Imageclass 2200 Advanced Copier                 0.428571
Fellowes Pb500 Electric Punch Plastic Comb Bind...    0.428571
Cisco Telepresence System Ex90 Videoconferencin...    0.428571
Hon 5400 Series Task Chairs For Big And Tall          0.428571
Gbc Docubind Tl300 Electric Binding System            0.428571
Gbc Ibimaster 500 Manual Proclick Binding System      0.428571
Hewlett Packard Laserjet 3310 Copier                  0.428571
Hp Designjet T520 Inkjet Large Format Printer -...    0.428571
Gbc Docubind P400 Electric Binding System             0.428571
High Speed Automatic Electric Letter Opener           0.428571

In [183]:
shipping_efficiency = df.groupby('Ship Mode').agg({
    'Ship Delay': 'mean',      
    'Sales': 'sum',            
    'Is_Profitable': 'mean'    
}).sort_values(by='Ship Delay')

print(shipping_efficiency)

                Ship Delay         Sales  Is_Profitable
Ship Mode
Same Day          0.044610  1.252190e+05            1.0
First Class       2.179214  3.455723e+05            1.0
Second Class      3.249211  4.499142e+05            1.0
Standard Class    5.008363  1.340831e+06            1.0

In [184]:
monthly_trend = df.groupby(['Order Year', 'Order Month'])['Sales'].sum().unstack()

In [185]:
invalid_dates = df[df['Ship Date'] < df['Order Date']]
print(f"عدد الأخطاء الزمنية: {len(invalid_dates)}")

عدد الأخطاء الزمنية: 0

In [186]:
invalid_profits = df[df['Profit'] > df['Sales']]
print(f"عدد الأخطاء في حساب الربح: {len(invalid_profits)}")

عدد الأخطاء في حساب الربح: 0

In [187]:
zero_cost = df[(df['Sales'] > 0) & (df['Estimated Cost'] <= 0)]
print(f"عدد الطلبات بتكلفة غير منطقية (0 أو أقل): {len(zero_cost)}")

عدد الطلبات بتكلفة غير منطقية (0 أو أقل): 0

In [188]:
zip_check = df.groupby('Postal Code')['City'].nunique()
invalid_zips = zip_check[zip_check > 1]
print(f"عدد الرموز البريدية المرتبطة بأكثر من مدينة: {len(invalid_zips)}")

عدد الرموز البريدية المرتبطة بأكثر من مدينة: 1

In [189]:
zip_check = df.groupby('Postal Code')['City'].nunique()
invalid_zip_list = zip_check[zip_check > 1].index.tolist()

duplicate_cities = df[df['Postal Code'].isin(invalid_zip_list)][['Postal Code', 'City']].drop_duplicates()
print(duplicate_cities)

     Postal Code       City
481        92024  San Diego
1113       92024  Encinitas

In [190]:
df.loc[df['Postal Code'] == '92024', 'City'] = 'Encinitas'

check_again = df.groupby('Postal Code')['City'].nunique()
print(f"عدد الرموز المرتبطة بأكثر من مدينة الآن: {check_again[check_again > 1].count()}")

عدد الرموز المرتبطة بأكثر من مدينة الآن: 0

In [191]:
cols_order = [
    'Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 
    'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 
    'State', 'Postal Code', 'Region', 'Product ID', 'Category', 
    'Sub-Category', 'Product Name', 'Sales', 'Profit', 'Estimated Cost',
    'Profit Margin %', 'ROI_Factor', 'Quantity', 'Ship Delay', 'Shipping Class',
    'Order Year', 'Order Month', 'Order Day', 'Sales_Performance', 'Is_Profitable'
]
df = df[ [c for c in cols_order if c in df.columns] ]

In [192]:
df_for_sql = df.copy()
for col in df_for_sql.select_dtypes('category').columns:
    df_for_sql[col] = df_for_sql[col].astype(str)

In [194]:
df.to_csv('superstore_clean.csv', index=False, encoding='utf-8-sig')

print("✅ تم تصدير الملف بنجاح باسم: superstore_clean.csv")
print(f"📊 حجم البيانات المصدرة: {df.shape[0]} صف و {df.shape[1]} عمود.")

✅ تم تصدير الملف بنجاح باسم: superstore_clean.csv
📊 حجم البيانات المصدرة: 9800 صف و 29 عمود.